### ISSUE TITLE
Please fix dependency on libxcb. It is very loose and it hurts!

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/cairo-feedstock#59] opened 2021-02-26 00:48 UTC
```
root@0c38ad9ac566:/# /base_home/conda-latest-linux-64.exe \
    search --info -c conda-forge cairo=1.16 | grep libxcb       

  - libxcb
  - libxcb
  - libxcb
  - libxcb
  - libxcb
  - libxcb
  - libxcb
  - libxcb
  - libxcb
  - libxcb
```

:cry: :crying_cat_face: :sob:

**Comment by pkgw** [comment] 2021-02-26 01:43
See also: https://github.com/conda-forge/xorg-libx11-feedstock/issues/24

**Comment by pkgw** [comment] 2021-03-22 14:53
I'm going to close this issue because the libxcb pinning isn't really the root cause of the issues mentioned above, in my view. To keep the discussion all in one place, any followups happen in the discussion for conda-forge/graphviz-feedstock#35.

**Closed by pkgw** 2021-03-22 14:53 UTC
